name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code style with Ruff
      uses: chartboost/ruff-action@v1
      with:
        src: "./src"

    - name: Run tests
      run: |
        pytest tests/tokenizer_tests.py tests/tests.py
